import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./_component/Header";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Formify Ai",
  description: "Generated by create next app",
  icons : {
    icon : "/favicon.ico",
    shortcut: "/favicon.ico"
  }
};

export default function RootLayout({ children }) {
  return (
   
    <html
      lang="en"
      data-theme="sunset"
      className={`${poppins.variable} font-sans min-h-full flex flex-col`}
    >
      <body className={`${poppins.className} min-h-full flex flex-col`}>
        <Header />
        {children}
      </body>
    </html>
    
  );
}